# This file is part of robotframework-smtplibrary.
# https://github.io/lucamaro/robotframework-smtplibrary

# Licensed under the Apache License 2.0 license:
# http://www.opensource.org/licenses/Apache-2.0
# Copyright (c) 2016, Luca Maragnani <luca.maragnani@gmail.com>

language: python

python:
    - "3.6"

install:
    # install python requirements
    - pip install .
    - pip install python-coveralls
    - pip install pytest-cov

script:
    # run tests
    - pytest --cov src -v
#    - make test

after_success:
  - coveralls
