language: python

python:
    - "3.6"

install:
    # install python requirements
    - pip install .
    - pip install python-coveralls
    - pip install pytest-cov

script:
    # run tests
    - pytest --cov SmtpLibrary -v tests/base.py

after_success:
  - coveralls
